# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/imgs/avatar/', verbose_name='头像路径'),
        ),
    ]
