# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/imgs/default.jpeg', null=True, upload_to='static/imgs', verbose_name='头像'),
        ),
    ]
