# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180105_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, '游戏'), (2, '编程'), (3, '生活'), (4, '社交')], default=None, verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Category', verbose_name='博客分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='static/imgs/articles/small', verbose_name='文章图片'),
        ),
    ]
