# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20171226_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs', verbose_name='头像'),
        ),
    ]
