# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20171228_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='头像路径'),
        ),
    ]
