# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20171228_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='专栏标题')),
                ('img', models.FileField(upload_to='', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64, verbose_name='商品标题')),
                ('brief', models.CharField(max_length=128, verbose_name='简介')),
                ('img', models.FileField(upload_to='', verbose_name='图片')),
                ('price', models.FloatField(max_length=16, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='关键字名称')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword2Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Column', verbose_name='专栏')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Keyword', verbose_name='关键字')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword2Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Goods', verbose_name='商品')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Keyword', verbose_name='关键字')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='columns',
            field=models.ManyToManyField(related_name='c2k', through='repository.Keyword2Column', to='repository.Column', verbose_name='专栏'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='goods',
            field=models.ManyToManyField(related_name='g2k', through='repository.Keyword2Goods', to='repository.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='goods',
            name='keywords',
            field=models.ManyToManyField(related_name='k2g', through='repository.Keyword2Goods', to='repository.Keyword', verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='column',
            name='keywords',
            field=models.ManyToManyField(related_name='k2c', through='repository.Keyword2Column', to='repository.Keyword', verbose_name='关键字'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword2goods',
            unique_together=set([('keyword', 'goods')]),
        ),
        migrations.AlterUniqueTogether(
            name='keyword2column',
            unique_together=set([('keyword', 'column')]),
        ),
    ]
