# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20180103_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64, verbose_name='广告标题')),
                ('url', models.CharField(max_length=64, verbose_name='链接')),
                ('img', models.FileField(upload_to='', verbose_name='图片')),
            ],
        ),
    ]
