# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='column',
            name='link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='链接'),
        ),
    ]
