# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_ad_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.CharField(max_length=16, null=True, verbose_name='类别'),
        ),
    ]
