# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20180103_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brief',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='简介'),
        ),
    ]
