# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20180103_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='caption',
            field=models.CharField(max_length=32, unique=True, verbose_name='关键字名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='caption',
            field=models.CharField(max_length=32, unique=True, verbose_name='权限标题'),
        ),
        migrations.AlterField(
            model_name='role',
            name='caption',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(max_length=32, unique=True, verbose_name='组名'),
        ),
    ]
