# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='permission2action2role',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='permission2action2role',
            name='action',
        ),
        migrations.RemoveField(
            model_name='permission2action2role',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permission2action2role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user2role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user2role',
            name='user',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Permission2Action2Role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User2Role',
        ),
    ]
